import {
  TO_FULL_WIDTH,
  TO_FULL_WIDTH_ALPHABET,
  TO_FULL_WIDTH_KANA,
  TO_FULL_WIDTH_NUMBER,
  TO_FULL_WIDTH_SIGN,
  TO_FULL_WIDTH_SPACE,
} from '../retypeToFullWidth/constants';
import {
  TO_HALF_WIDTH,
  TO_HALF_WIDTH_ALPHABET,
  TO_HALF_WIDTH_KANA,
  TO_HALF_WIDTH_NUMBER,
  TO_HALF_WIDTH_SIGN,
  TO_HALF_WIDTH_SPACE,
} from '../retypeToHalfWidth/constants';
import { TO_HIRAGANA } from '../retypeToHiragana/constants';
import {
  TO_HIRAGANA_SEION,
  TO_HIRAGANA_SEION_FROM_DAKUON,
  TO_HIRAGANA_SEION_FROM_SOKUON,
  TO_HIRAGANA_SEION_FROM_YOUON,
} from '../retypeToHiraganaSeion/constants';
import { TO_KATAKANA } from '../retypeToKatakana/constants';
import {
  TO_KATAKANA_SEION,
  TO_KATAKANA_SEION_FROM_DAKUON,
  TO_KATAKANA_SEION_FROM_SOKUON,
  TO_KATAKANA_SEION_FROM_YOUON,
} from '../retypeToKatakanaSeion/constants';

export const TransformationType = {
  [TO_FULL_WIDTH.id]: TO_FULL_WIDTH.id,
  [TO_FULL_WIDTH_ALPHABET.id]: TO_FULL_WIDTH_ALPHABET.id,
  [TO_FULL_WIDTH_NUMBER.id]: TO_FULL_WIDTH_NUMBER.id,
  [TO_FULL_WIDTH_SIGN.id]: TO_FULL_WIDTH_SIGN.id,
  [TO_FULL_WIDTH_SPACE.id]: TO_FULL_WIDTH_SPACE.id,
  [TO_FULL_WIDTH_KANA.id]: TO_FULL_WIDTH_KANA.id,
  [TO_HALF_WIDTH.id]: TO_HALF_WIDTH.id,
  [TO_HALF_WIDTH_ALPHABET.id]: TO_HALF_WIDTH_ALPHABET.id,
  [TO_HALF_WIDTH_NUMBER.id]: TO_HALF_WIDTH_NUMBER.id,
  [TO_HALF_WIDTH_SIGN.id]: TO_HALF_WIDTH_SIGN.id,
  [TO_HALF_WIDTH_SPACE.id]: TO_HALF_WIDTH_SPACE.id,
  [TO_HALF_WIDTH_KANA.id]: TO_HALF_WIDTH_KANA.id,
  [TO_HIRAGANA.id]: TO_HIRAGANA.id,
  [TO_HIRAGANA_SEION.id]: TO_HIRAGANA_SEION.id,
  [TO_HIRAGANA_SEION_FROM_DAKUON.id]: TO_HIRAGANA_SEION_FROM_DAKUON.id,
  [TO_HIRAGANA_SEION_FROM_SOKUON.id]: TO_HIRAGANA_SEION_FROM_SOKUON.id,
  [TO_HIRAGANA_SEION_FROM_YOUON.id]: TO_HIRAGANA_SEION_FROM_YOUON.id,
  [TO_KATAKANA.id]: TO_KATAKANA.id,
  [TO_KATAKANA_SEION.id]: TO_KATAKANA_SEION.id,
  [TO_KATAKANA_SEION_FROM_DAKUON.id]: TO_KATAKANA_SEION_FROM_DAKUON.id,
  [TO_KATAKANA_SEION_FROM_SOKUON.id]: TO_KATAKANA_SEION_FROM_SOKUON.id,
  [TO_KATAKANA_SEION_FROM_YOUON.id]: TO_KATAKANA_SEION_FROM_YOUON.id,
} as const;

export type TransformationType =
  (typeof TransformationType)[keyof typeof TransformationType];

export const TRANSFORMERS = {
  [TO_FULL_WIDTH.id]: TO_FULL_WIDTH,
  [TO_FULL_WIDTH_ALPHABET.id]: TO_FULL_WIDTH_ALPHABET,
  [TO_FULL_WIDTH_NUMBER.id]: TO_FULL_WIDTH_NUMBER,
  [TO_FULL_WIDTH_SIGN.id]: TO_FULL_WIDTH_SIGN,
  [TO_FULL_WIDTH_SPACE.id]: TO_FULL_WIDTH_SPACE,
  [TO_FULL_WIDTH_KANA.id]: TO_FULL_WIDTH_KANA,
  [TO_HALF_WIDTH.id]: TO_HALF_WIDTH,
  [TO_HALF_WIDTH_ALPHABET.id]: TO_HALF_WIDTH_ALPHABET,
  [TO_HALF_WIDTH_NUMBER.id]: TO_HALF_WIDTH_NUMBER,
  [TO_HALF_WIDTH_SIGN.id]: TO_HALF_WIDTH_SIGN,
  [TO_HALF_WIDTH_SPACE.id]: TO_HALF_WIDTH_SPACE,
  [TO_HALF_WIDTH_KANA.id]: TO_HALF_WIDTH_KANA,
  [TO_HIRAGANA.id]: TO_HIRAGANA,
  [TO_HIRAGANA_SEION.id]: TO_HIRAGANA_SEION,
  [TO_HIRAGANA_SEION_FROM_DAKUON.id]: TO_HIRAGANA_SEION_FROM_DAKUON,
  [TO_HIRAGANA_SEION_FROM_SOKUON.id]: TO_HIRAGANA_SEION_FROM_SOKUON,
  [TO_HIRAGANA_SEION_FROM_YOUON.id]: TO_HIRAGANA_SEION_FROM_YOUON,
  [TO_KATAKANA.id]: TO_KATAKANA,
  [TO_KATAKANA_SEION.id]: TO_KATAKANA_SEION,
  [TO_KATAKANA_SEION_FROM_DAKUON.id]: TO_KATAKANA_SEION_FROM_DAKUON,
  [TO_KATAKANA_SEION_FROM_SOKUON.id]: TO_KATAKANA_SEION_FROM_SOKUON,
  [TO_KATAKANA_SEION_FROM_YOUON.id]: TO_KATAKANA_SEION_FROM_YOUON,
};
